spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac_system
    username: root
    password: "030166"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB



#
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
server:
  port: 9000
